### ISSUE TITLE
explain where to get xcodebuild from in README.md

### ISSUE THREAD

**Issue by krichter722** [iterate-ch/rococoa#16]
`mvn install` fails with `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (build-native) on project rococoa-core: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "xcodebuild" (in directory "/mnt/richtercloud/sources/rococoa/rococoa/rococoa-core"): error=2, Datei oder Verzeichnis nicht gefunden
[ERROR] around Ant part ...<exec dir="." executable="xcodebuild" failonerror="true">... @ 4:60 in /mnt/richtercloud/sources/rococoa/rococoa/rococoa-core/target/antrun/build-main.xml`

**Comment by dkocher** [comment]
You need to install [Xcode](https://developer.apple.com/download/).

**Comment by krichter722** [comment]
Please note that the issue is not resolved which might be your decision.
