### ISSUE TITLE
Support for Apple silicon

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/rococoa#20]
Dependent on https://github.com/java-native-access/jna/pull/1238

**Comment by ccidral** [comment]
@dkocher Just curious, were you able to build and use rococoa under Apple silicon? I see that java-native-access/jna#1238 has been closed.

**Comment by dkocher** [comment]
There are several things to be sorted out
- Make sure JNA has no test failures on Apple silicon. See [#1323](https://github.com/java-native-access/jna/issues/1323)
- Always use `objc_msgSend` on Apple silicon to be patched in [MsgSendHandler](https://github.com/iterate-ch/rococoa/blob/9a85ee93e64d7dca9800a88178c18f1f27221302/rococoa/rococoa-core/src/main/java/org/rococoa/internal/MsgSendHandler.java)
- Fix several test failures in Rococoa possibly caused by not type safe calling `objc_msgSend `. 
 
> To fix dynamic-dispatching issues in your code, define a type-safe function pointer instead of calling objc_msgSend directly. Refer to [Enable Strict Type Enforcement for Dynamic Method Dispatching](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code)

**Comment by dkocher** [comment]
> * Fix several test failures in Rococoa possibly caused by not type safe calling `objc_msgSend `.
> 
> > To fix dynamic-dispatching issues in your code, define a type-safe function pointer instead of calling objc_msgSend directly. Refer to [Enable Strict Type Enforcement for Dynamic Method Dispatching](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code)

Not sure if this is actually an issue with JNA using [libffi](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Function.java#L323).

**Comment by dkocher** [comment]
We are making [progress](https://github.com/java-native-access/jna/issues/1394#issuecomment-962682736).

**Comment by dkocher** [comment]
Additional helpful documentation in [Managing Functions and Function Pointers
](https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture/managing_functions_and_function_pointers?language=objc).
